# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'HXWindAdapter-iOS-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HXWindAdapter-iOS-Example
  pod 'HXToBidAdapter', :path => '../../HXWindAdapter-iOS'

  target 'HXWindAdapter-iOS-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HXWindAdapter-iOS-ExampleUITests' do
    # Pods for testing
  end

end
